[project]
name = "milvus-colpali"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colpali-engine>=0.3.8",
    "pdf2image>=1.17.0",
    "pillow>=11.1.0",
    "pymilvus>=2.5.5",
]
